name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11
        enable-cache: true
    - name: Install dependencies
      run: |
        uv pip install hatch
    - name: Run pre-commit
      run: hatch run pre-commit run --all-files
