name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish release package to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pydexcom
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Build package distributions
      run: python3 -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/